#GCC PATH
GCC_DIR =

#COMPILER
CC = $(GCC_DIR)gcc
CXX = $(GCC_DIR)g++
AR = $(GCC_DIR)ar

ifeq "$(WiBench_INSTALL_DIR)" ""
$(error Please specify the wibench installation directory in the system environment variable WiBench_INSTALL_DIR)
else
KERNEL_DIR := $(WiBench_INSTALL_DIR)/src/kernel
APP_DIR := $(WiBench_INSTALL_DIR)/src/app
UTIL_DIR := $(WiBench_INSTALL_DIR)/src/util
CHANNEL_DIR := $(WiBench_INSTALL_DIR)/src/channel

KERNEL_BUILD_DIR := $(WiBench_INSTALL_DIR)/build/kernel 
APP_BUILD_DIR := $(WiBench_INSTALL_DIR)/build/app

INC_FLAGS = -I$(WiBench_INSTALL_DIR)/src/include

CC_DEBUG_FLAGS=
CXX_DEBUG_FLAGS = 

CC_OPT_FLAGS =
CXX_OPT_FLAGS = -O3

CCFLAGS += $(CC_DEBUG_FLAGS)
CCFLAGS += $(CC_OPT_FLAGS)
CCFLAGS += $(INC_FLAGS)

CXXFLAGS += $(CXX_DEBUG_FLAGS)
CXXFLAGS += $(CXX_OPT_FLAGS)
CXXFLAGS += $(INC_FLAGS)
endif
